Rebrand Boyfriend
LabsDevelopment/Octobot pull request #128
Opened 2023-09-29 20:17 UTC by mctaylors

We're moving!

Also, @Octol1ttle, please rename this repository to `Octobot` before approving changes.

2023-09-29 20:20 UTC, mctaylors commented
Checks are failing because
> Unable to find target solution file in path /home/runner/work/Boyfriend/Boyfriend/Boyfriend.sln

2023-09-29 20:25 UTC, mctaylors commented
> Also, @Octol1ttle, please rename this repository to Octobot before approving changes.

https://github.com/LabsDevelopment/Boyfriend/pull/128/commits/f6bfaba98ca1b9de4a29b1a4fe5ff467aa9a5ddb Oh, and _also_ teams.

2023-09-30 07:22 UTC, Octol1ttle requested changes

2023-09-30 07:22 UTC, Octol1ttle commented on docs/README.md
> +Veemo! I'm a general-purpose bot for moderation (formerly known as Octobot) written by [@Octol1ttle](https://github.com/Octol1ttle) in C# and Remora.Discord
"formerly" means "previously", "in the past"

2023-09-30 07:22 UTC, Octol1ttle commented on locale/Messages.resx
> +      <value>Voomy!</value>
```suggestion
      <value>Woomy!</value>
```

2023-09-30 07:22 UTC, Octol1ttle commented on locale/Messages.resx
> +      <value>Ngyes!</value>
note: "Woomy" and "Ngyes" are used by Inklings, Octolings use different voicelines

(if this is intentional, you don't have to change this)

2023-09-30 07:31 UTC, mctaylors commented on docs/README.md
> +Veemo! I'm a general-purpose bot for moderation (formerly known as Octobot) written by [@Octol1ttle](https://github.com/Octol1ttle) in C# and Remora.Discord
i accidentally wrote "Octobot"

2023-09-30 07:35 UTC, mctaylors commented on locale/Messages.resx
> +      <value>Ngyes!</value>
if you want, you can suggest what kind of sound there will be.
Most likely I won't change it because it's an iconic sound.

2023-09-30 07:50 UTC, Octol1ttle requested changes

2023-09-30 07:50 UTC, Octol1ttle commented on Octobot.csproj
>          <Description>A legacy-driven Discord bot written in C#</Description>
we are no longer legacy-driven, actually.

2023-09-30 07:50 UTC, Octol1ttle commented on docs/README.md
> +Veemo! I'm a general-purpose bot for moderation (formerly known as Boyfriend) written by [@Octol1ttle](https://github.com/Octol1ttle) in C# and Remora.Discord
> written by @Octol1ttle 
we're a team now, so I think it's best to omit this

2023-09-30 07:50 UTC, Octol1ttle commented on locale/Messages.ru.resx
> +    <value>О Octobot</value>
@Apceniy double check
```suggestion
    <value>Об Octobot</value>
```

2023-09-30 07:50 UTC, Octol1ttle commented on locale/Messages.ru.resx
> +    <value>разработчик и дизайнер, создатель Octobot's Wiki</value>
```suggestion
    <value>разработчик и дизайнер, создатель вики Octobot</value>
```

2023-09-30 07:50 UTC, Octol1ttle commented on locale/Messages.tt-ru.resx
> +    <value>немного о Octobot</value>
```suggestion
    <value>немного об Octobot</value>
```

2023-09-30 07:50 UTC, Octol1ttle commented on locale/Messages.tt-ru.resx
> +    <value>скучный девелопер + дизайнер создавший Octobot's Wiki</value>
```suggestion
    <value>скучный девелопер + дизайнер создавший вики Octobot</value>
```

2023-09-30 07:57 UTC, mctaylors commented on locale/Messages.ru.resx
> +    <value>разработчик и дизайнер, создатель Octobot's Wiki</value>
Wiki page is actually called "Octobot's Wiki". If you really don't like this, tell me, I will rename it.

2023-09-30 07:58 UTC, mctaylors commented on locale/Messages.tt-ru.resx
> +    <value>скучный девелопер + дизайнер создавший Octobot's Wiki</value>
https://github.com/LabsDevelopment/Boyfriend/pull/128#discussion_r1341925798

2023-09-30 08:00 UTC, Octol1ttle commented on locale/Messages.ru.resx
> +    <value>разработчик и дизайнер, создатель Octobot's Wiki</value>
since this is intentional, leave it as-is

2023-09-30 08:01 UTC, mctaylors commented
I'll resolve the conversations as soon as possible, I don't have any free time right now.

2023-09-30 08:17 UTC, mctaylors commented
> https://github.com/LabsDevelopment/Boyfriend/commit/f6bfaba98ca1b9de4a29b1a4fe5ff467aa9a5ddb Oh, and also teams.

https://github.com/LabsDevelopment/Boyfriend/pull/128/commits/27a1778cf16fefdd0955edbe4a6e7f96615aebde Including description on repository page.

2023-09-30 10:09 UTC, Octol1ttle submitted a review, later dismissed
do not merge yourself, I will merge this when all outside work is completed

2023-09-30 13:57 UTC, Octol1ttle approved these changes

2023-09-30 13:58 UTC, merged