Update /random
LabsDevelopment/Octobot pull request #138
Opened 2023-10-01 16:51 UTC by mctaylors

Updates in /random:
- Set default minimum number to 0
- Slightly redesign embed
- Recolor & display a message when user tries to use exact same number in maximum and minimum fields for some reason.

2023-10-01 17:18 UTC, Octol1ttle commented on locale/Messages.resx
> +  <data name="RandomObvious" xml:space="preserve">
rename to `RandomMinMaxSame`

2023-10-02 08:12 UTC, mctaylors commented
I should stop doing that.

2023-10-02 08:39 UTC, mctaylors commented
Don't do mobile editing, kids.

2023-10-02 09:39 UTC, Octol1ttle commented on src/Commands/ToolsCommandGroup.cs
> +        var embedColor = ColorsList.Blue;
newline please

2023-10-02 10:07 UTC, Octol1ttle commented on src/Commands/ToolsCommandGroup.cs
> +
mobile editing moment
```suggestion

```

2023-10-02 14:39 UTC, Octol1ttle commented on src/Commands/ToolsCommandGroup.cs
> +        var min = Math.Min(first, second);
```suggestion
        var min = Math.Min(first, second);
        var max = Math.Max(first, second);
```

2023-10-02 14:41 UTC, Octol1ttle approved these changes
now wait for @Apceniy

2023-10-02 18:13 UTC, Octol1ttle approved these changes

2023-10-03 11:31 UTC, Octol1ttle commented on src/Commands/ToolsCommandGroup.cs
> +            description.Append(' ').Append(Messages.Default);
Put this into nested `if`-s

2023-10-03 12:25 UTC, Octol1ttle submitted a review, later dismissed

2023-10-04 12:09 UTC, Apceniy requested changes
Replace magic 0s with a constant for the default value with meaningful name that reflects the purpose, improves flexibility for the possible future changes and reduces human errors

2023-10-04 12:09 UTC, Apceniy commented on src/Commands/ToolsCommandGroup.cs
> +        var second = secondNullable ?? 0;
```suggestion
        var secondDefault = 0;
        var second = secondNullable ?? secondDefault;
```

2023-10-04 12:09 UTC, Apceniy commented on src/Commands/ToolsCommandGroup.cs
> +        if (secondNullable is null && first >= 0)
```suggestion
        if (secondNullable is null && first >= secondDefault)
```

2023-10-04 12:09 UTC, Apceniy commented on src/Commands/ToolsCommandGroup.cs
> +        if (secondNullable is null && first < 0)
```suggestion
        if (secondNullable is null && first < secondDefault)
```

2023-10-04 12:14 UTC, Octol1ttle submitted a review, later dismissed

2023-10-04 12:16 UTC, Apceniy commented on src/Commands/ToolsCommandGroup.cs
> +        const int secondDefault = 0;
we're working with longs
```suggestion
        const long secondDefault = 0;
```

2023-10-04 12:32 UTC, merged