Add StringBuilder for SongUpdateService
LabsDevelopment/Octobot pull request #139
Opened 2023-10-01 17:29 UTC by mctaylors

I added a StringBuilder for SongUpdateService for better activity status configuration. So now you can add some characters if you want, or even swap the song title and author.

Also songs are now displaying in Splatoon™ style.
![image](https://github.com/LabsDevelopment/Octobot/assets/95250141/9ac14ae1-b54f-455d-9aa6-da1752954d68)

2023-10-01 18:49 UTC, Octol1ttle requested changes

2023-10-01 18:49 UTC, Octol1ttle commented on src/Services/Update/SongUpdateService.cs
> +            var builder = new StringBuilder().Append(nextSong.Name).Append(" / ").Append(nextSong.Author);
ever heard of string interpolation?

2023-10-01 18:49 UTC, Octol1ttle commented on src/Services/Update/SongUpdateService.cs
> +    private static readonly (string Name, string Author, TimeSpan Duration)[] SongList =
please swap Name and Author

2023-10-02 07:34 UTC, mctaylors commented on src/Services/Update/SongUpdateService.cs
> +    private static readonly (string Name, string Author, TimeSpan Duration)[] SongList =
That will be kinda confusing because of this

> Also songs are now displaying in Splatoon™ style.

2023-10-02 09:35 UTC, Octol1ttle commented on src/Services/Update/SongUpdateService.cs
> +    private static readonly (string Name, string Author, TimeSpan Duration)[] SongList =
Just because Splatoon does something doesn't mean we should do exactly the same. The format has been the same for years at this point, why change it?

2023-10-02 09:44 UTC, mctaylors commented on src/Services/Update/SongUpdateService.cs
> +    private static readonly (string Name, string Author, TimeSpan Duration)[] SongList =
I mean, we'll get used to it, and if I change it, it'll be confusing when changing the song list.

2023-10-02 09:47 UTC, Octol1ttle commented
> Just because Splatoon does something doesn't mean we should do exactly the same. The format has been the same for years at this point, why change it?

2023-10-02 10:00 UTC, mctaylors commented
_sigh_

2023-10-02 10:04 UTC, Octol1ttle commented
You do not appear to understand that I'm against EVERY change in this pull request. You got tunnel vision again, for the millionth time in a row. Please DO NOT re-open this pull request or you will have your write access removed.

2023-10-02 10:06 UTC, mctaylors commented
> You do not appear to understand that I'm against EVERY change in this pull request. You got tunnel vision again, for the millionth time in a row. Please DO NOT re-open this pull request or you will have your write access removed.

go ahead

2023-10-02 14:37 UTC, Octol1ttle approved these changes

2023-10-02 14:41 UTC, merged