Add /timestamp
LabsDevelopment/Octobot pull request #140
Opened 2023-10-02 20:55 UTC by mctaylors

Original idea from @Octol1ttle

2023-10-02 21:54 UTC, mctaylors commented
@Octol1ttle, looks like pull-request-size bot is malfunctioning...

2023-10-03 11:34 UTC, Octol1ttle requested changes

2023-10-03 11:34 UTC, Octol1ttle commented on src/Commands/ToolsCommandGroup.cs
> +    /// <param name="offset">The offset to count timestamp.</param>
```suggestion
    ///     A slash command that shows the current timestamp with an optional offset in all styles supported by Discord.
    /// </summary>
    /// <param name="offset">The offset for the current timestamp.</param>
```

2023-10-03 11:34 UTC, Octol1ttle commented on src/Commands/ToolsCommandGroup.cs
> +    [Description("Gets timestamp")]
```suggestion
    [Description("Shows a timestamp in all styles")]
```

2023-10-03 11:34 UTC, Octol1ttle commented on src/Commands/ToolsCommandGroup.cs
> +    private async Task<Result> SendRandomNumberAsync(TimeSpan? offset, IUser user, CancellationToken ct)
`SendRandomNumberAsync`?

2023-10-03 11:34 UTC, Octol1ttle commented on src/Commands/ToolsCommandGroup.cs
> +        }
Put result of `Markdown.Timestamp` in a variable (put text cursor on the method call and press Ctrl+Alt+V in Rider)

2023-10-03 11:59 UTC, Octol1ttle commented on src/Commands/ToolsCommandGroup.cs
> +    };
Put this above `ExecuteTimestampAsync`

2023-10-03 11:59 UTC, Octol1ttle commented on src/Commands/ToolsCommandGroup.cs
> +        [Description("Add an offset from now")]
```suggestion
        [Description("Offset from current time")]
```

2023-10-03 12:07 UTC, Octol1ttle approved these changes

2023-10-03 12:07 UTC, merged