No more edited bots message in log channel
LabsDevelopment/Octobot pull request #202
Opened 2023-11-29 23:12 UTC by neroduckale

If the creator of the modified message is a bot, then the octobot does not display a message about the change

2023-11-30 00:18 UTC, mctaylors requested changes
Please resolve failing checks first.

2023-11-30 00:47 UTC, mctaylors approved these changes
LGTM

2023-11-30 09:26 UTC, Octol1ttle requested changes

2023-11-30 09:26 UTC, Octol1ttle commented on src/Responders/MessageEditedResponder.cs
> +        if (gatewayEvent.Author.Value.IsBot == true)
we don't use `== true`/`== false`

2023-11-30 21:44 UTC, neroduckale commented on src/Responders/MessageEditedResponder.cs
> +        if (isBot)
Maybe you meant OrDefault(false)?

2023-11-30 21:53 UTC, mctaylors commented on src/Responders/MessageEditedResponder.cs
> +        if (isBot)
Yes, thanks for the correction. I don't have access to my computer right now due to some technical problems, so I might be a bit wrong.

2023-12-04 09:09 UTC, Octol1ttle commented on src/Responders/MessageEditedResponder.cs
> +        if (author.IsBot.OrDefault(false))
This can be inlined
```suggestion
        if (gatewayEvent.Author.IsDefined(out var author) && author.IsBot.OrDefault(false))
```

2023-12-17 16:50 UTC, Octol1ttle commented on src/Responders/MessageEditedResponder.cs
> +        }
move up to other successful returns

2023-12-17 16:51 UTC, Octol1ttle reviewed
if able, refactor the `if` chain so that the call to `GetSettings` is the last one in the chain

2023-12-17 17:00 UTC, Octol1ttle approved these changes

2023-12-17 17:02 UTC, mctaylors approved these changes

2023-12-17 17:02 UTC, merged