Add link to original message in listremind
LabsDevelopment/Octobot pull request #203
Opened 2023-12-01 01:48 UTC by neroduckale

/listremind now has a link to a message with the creation of a reminder for messages like "this"

2023-12-02 09:26 UTC, mctaylors commented on src/Commands/RemindCommandGroup.cs
> +                .AppendLine(string.Format(Messages.ReminderTime, Markdown.Timestamp(reminder.At)))
æ

2023-12-02 09:29 UTC, mctaylors commented on src/Commands/RemindCommandGroup.cs
> +                .AppendLine(string.Format(Messages.ReminderTime, Markdown.Timestamp(reminder.At)))
Please remove linebreak before `.AppendLine`

2023-12-02 09:40 UTC, Octol1ttle requested changes

2023-12-02 09:40 UTC, Octol1ttle commented on src/Data/Reminder.cs
> +    public string Message { get; init; }
This variable name can be confused with `Text`

2023-12-02 09:40 UTC, Octol1ttle commented on src/Commands/RemindCommandGroup.cs
> +        var messageId = message.Entity.ID.Value;
Please check that the message was sent successfully first

2023-12-02 09:40 UTC, Octol1ttle commented on src/Commands/RemindCommandGroup.cs
> +        var builderMessage = new StringBuilder().AppendLine(
Unnecessary string builder construction

2023-12-02 09:40 UTC, Octol1ttle commented on src/Commands/RemindCommandGroup.cs
> +                Message = builderMessage.ToString()
No need to store the whole link, keep only the original message ID and construct the link when the reminder is sent

2023-12-02 11:10 UTC, neroduckale commented
TODO: Add link when reminder is off

2023-12-03 20:48 UTC, mctaylors requested changes

2023-12-03 20:48 UTC, mctaylors commented on src/Commands/RemindCommandGroup.cs
> +                .AppendLine(string.Format(Messages.ReminderTime, Markdown.Timestamp(reminder.At)))
I mean, I need 
```csharp
.Append(" - ").AppendLine(string.Format(Messages.ReminderTime, Markdown.Timestamp(reminder.At)))
```
not
```csharp
.Append(" - ")
/* this linebreak */.AppendLine(string.Format(Messages.ReminderTime, Markdown.Timestamp(reminder.At)))
```

Unfortunately, I cannot make a suggestion because line 95 wasn't changed.

2023-12-03 20:48 UTC, mctaylors commented on src/Commands/RemindCommandGroup.cs
> +                );
```suggestion
                .Append(" - ").AppendLine(string.Format(
                    Messages.DescriptionActionJumpToMessage, $"https://discord.com/channels/{guildId.Value}/{reminder.Channel}/{reminder.MessageId}"));
```

2023-12-03 20:48 UTC, mctaylors commented on src/Commands/RemindCommandGroup.cs
> +        if (!messageResult.IsDefined(out var output)) { return (Result)messageResult; }
As I remember, we don't use one-line `if`s
```suggestion
        if (!messageResult.IsDefined(out var output))
        {
            return (Result)messageResult;
        }
```

2023-12-04 09:00 UTC, Octol1ttle commented on src/Commands/RemindCommandGroup.cs
> +    private async Task<Result> ListRemindersAsync(MemberData data, IUser executor, IUser bot, Snowflake guildId, CancellationToken ct)
As a guideline, usually more "top-level" variables go first (i.e. first guild-related variables, then channel-related variables, then user-related variables in order of `executor`, `target`, `bot`) with CancellationTokens always being at the very end

2023-12-04 09:23 UTC, mctaylors commented on src/Commands/RemindCommandGroup.cs
> +                );
#205

2023-12-05 16:59 UTC, neroduckale commented on src/Commands/RemindCommandGroup.cs
> +    private async Task<Result> ListRemindersAsync(MemberData data, IUser executor, IUser bot, Snowflake guildId, CancellationToken ct)
I think I got it, but if I didn't get it then you can always request changes

2023-12-05 17:02 UTC, neroduckale commented on src/Commands/RemindCommandGroup.cs
> +        var messageId = output.ID.Value;
If I understood you correctly, then I did everything right. if not, then request changes!

2023-12-05 17:54 UTC, Octol1ttle requested changes

2023-12-05 17:54 UTC, Octol1ttle commented on src/Commands/RemindCommandGroup.cs
> +        return (Result)messageResult;
linebreak before `return`

2023-12-05 17:54 UTC, Octol1ttle commented on src/Services/Update/MemberUpdateService.cs
> +            .WithTitle(
revert

2023-12-05 18:20 UTC, Octol1ttle commented on src/Commands/RemindCommandGroup.cs
> +        return (Result)messageResult;
This is a hack. The correct way to implement this would be using `IDiscordRestInteractionAPI#GetOriginalInteractionResponseAsync` with parameters received from `IInteractionCommandContext`

2023-12-07 11:39 UTC, mctaylors requested changes

2023-12-11 14:42 UTC, Octol1ttle requested changes

2023-12-11 14:42 UTC, Octol1ttle commented on src/Commands/RemindCommandGroup.cs
> +    private readonly IInteractionCommandContext _interactionContext;
Instead of adding a separate field, you can change the type of `_context` to `IInteractionCommandContext` and use that

2023-12-11 14:42 UTC, Octol1ttle commented on src/Commands/RemindCommandGroup.cs
> +        var applicationId = _interactionContext.Interaction.ApplicationID;
Move closer to usages

2023-12-11 14:42 UTC, Octol1ttle commented on src/Commands/RemindCommandGroup.cs
> +        }
Move embed creation and message send to the tail of this method

2023-12-11 14:42 UTC, Octol1ttle commented on src/Commands/RemindCommandGroup.cs
> +        var a = await _interactionApi.GetOriginalInteractionResponseAsync(applicationId, interactionToken, ct);
`responseResult`

2023-12-11 14:42 UTC, Octol1ttle commented on src/Commands/RemindCommandGroup.cs
> +        if (!a.IsDefined(out var interaction))
`out var response`

2023-12-11 14:42 UTC, Octol1ttle commented on src/Commands/RemindCommandGroup.cs
> +        var interactionValue = interaction.Interaction.Value.ID;
`GetOriginalInteractionResponseAsync` returns an `IMessage`, so you can use `ID` directly and inline it

2023-12-11 14:42 UTC, Octol1ttle commented on src/Services/Update/MemberUpdateService.cs
> +            .WithDescription(string.Format(builder.ToString()))
Unnecessary `string.Format` call

2023-12-11 14:54 UTC, neroduckale commented on src/Commands/RemindCommandGroup.cs
> +        var a = await _interactionApi.GetOriginalInteractionResponseAsync(applicationId, interactionToken, ct);
Haha, I forgot to change that.

2023-12-11 15:39 UTC, Octol1ttle requested changes

2023-12-11 15:39 UTC, Octol1ttle commented on src/Commands/RemindCommandGroup.cs
> +        var applicationId = _context.Interaction.ApplicationID;
Move even closer to usages or inline

2023-12-11 15:39 UTC, Octol1ttle commented on src/Commands/RemindCommandGroup.cs
> +        var builder = new StringBuilder().AppendBulletPointLine(string.Format(
Weird formatting, the only linebreaks here should be before `.Append` method calls

2023-12-11 15:39 UTC, Octol1ttle commented on src/Commands/RemindCommandGroup.cs
> +        var interactionValue = response.ID;
Inline

2023-12-11 15:39 UTC, Octol1ttle commented on src/Commands/RemindCommandGroup.cs
> +        return (Result)messageResult;
Use the `SendContextualEmbedResultAsync` extension method

2023-12-11 15:39 UTC, Octol1ttle commented on src/Commands/RemindCommandGroup.cs
> +            .WithFooter(string.Format(Messages.ReminderPosition, memberData.Reminders.Count + 1))
Since the embed is constructed after the reminder has been added, there is no longer any need to add `1` to the reminder count

2023-12-11 15:47 UTC, neroduckale commented on src/Commands/RemindCommandGroup.cs
> +        var builder = new StringBuilder().AppendBulletPointLine(string.Format(
Its @mctaylors changes, but ok

2023-12-11 16:44 UTC, Octol1ttle approved these changes

2023-12-11 16:59 UTC, mctaylors approved these changes

2023-12-11 20:20 UTC, Apceniy approved these changes

2023-12-11 20:38 UTC, merged