/remind: Return errors on negative or invalid TimeSpan value
LabsDevelopment/Octobot pull request #223
Opened 2023-12-17 20:05 UTC by mctaylors

Closes #154 and #220

2023-12-17 20:11 UTC, neroduckale approved these changes
nice fix

2023-12-17 21:02 UTC, neroduckale approved these changes
re-approve, nice code

2023-12-18 07:52 UTC, Octol1ttle requested changes
1) This does not close #220 because the core problem is not fixed (being that parsing errors are not relayed to the end user)
2) Even if we ignore that, the fix provided only applies to `/remind` and not other commands that accept a TimeSpan.

2023-12-18 07:52 UTC, Octol1ttle commented on locale/Messages.resx
> +  </data>
I would only use `InvalidTimeSpan` here. Negative TimeSpans do not make sense in any context

2023-12-18 07:52 UTC, Octol1ttle commented on src/Commands/RemindCommandGroup.cs
> +        return await ListRemindersAsync(data.GetOrCreateMemberData(executorId), guildId, executor, bot,
This pull request is *filled* with unnecessary formatting changes.

2023-12-18 07:52 UTC, Octol1ttle commented on src/Commands/RemindCommandGroup.cs
> +        string @in,
Now that the type is gone, the parameter name is confusing.

2023-12-18 07:52 UTC, Octol1ttle commented on src/Commands/RemindCommandGroup.cs
> +    private async Task<Result> AddReminderAsync(string strIn, string text, GuildData data,
Confusing parameter name

2023-12-18 07:52 UTC, Octol1ttle commented on src/Commands/RemindCommandGroup.cs
> +        var parseResult = await parser.TryParseAsync(strIn, ct);
If we are gonna stop using automatic parsing, might as well use a custom parser that can accept cyrillic letters as units (like the one used in Discord.NET edition)

2023-12-18 07:53 UTC, mctaylors commented on src/Commands/RemindCommandGroup.cs
> +        string @in,
Parameter name is also showing when using command. Renaming it will probably affect UX.

2023-12-18 08:08 UTC, Octol1ttle commented on src/Commands/RemindCommandGroup.cs
> +        string @in,
Good point. In that case, you can use the `[Option]` attribute to change the name that will display to the end user.

2023-12-18 09:42 UTC, mctaylors commented on src/Commands/RemindCommandGroup.cs
> +        return await ListRemindersAsync(data.GetOrCreateMemberData(executorId), guildId, executor, bot,
> It's better to reformat code only manually and only when you feel "this code is hard to read and I know how to make it better"

this code is hard to read and but now I don't know how to make it better

2023-12-28 08:38 UTC, Octol1ttle requested changes

2023-12-28 08:38 UTC, Octol1ttle commented on src/Commands/RemindCommandGroup.cs
> +        string stringIn,
confusing parameter name

2023-12-28 08:38 UTC, Octol1ttle commented on src/Commands/RemindCommandGroup.cs
> +        }
Parsing and input validation should be done in the preparation step

2023-12-28 08:38 UTC, Octol1ttle commented on src/Parsers/TimeSpanParser.cs
> +        var timeSpan = TimeSpan.Zero;
Use `TimeSpan.Zero` explicitly

2023-12-28 08:38 UTC, Octol1ttle commented on src/Parsers/TimeSpanParser.cs
> +        timeSpanString = timeSpanString.Trim();
Is this necessary? Doesn't Discord trim strings before sending them as slash command inputs?

2023-12-28 08:38 UTC, Octol1ttle commented on src/Parsers/TimeSpanParser.cs
> +                    : ParseFromRegex(timeSpan, key, groupValue, parsedGroupValue);
Invert condition

2023-12-28 08:38 UTC, Octol1ttle commented on src/Parsers/TimeSpanParser.cs
> +    public static Result<TimeSpan> TryParse(string timeSpanString, CancellationToken ct = default)
The method returns a `Result`, but no errors are returned

2023-12-28 08:38 UTC, Octol1ttle commented on locale/Messages.ru.resx
> +      <value>Указано некорректное время.</value>
```suggestion
      <value>Неправильно указано время!</value>
```

2023-12-28 08:38 UTC, Octol1ttle commented on locale/Messages.resx
> +      <value>Incorrect time specified.</value>
```suggestion
      <value>Time specified incorrectly!</value>
```

2023-12-28 08:50 UTC, mctaylors commented on src/Parsers/TimeSpanParser.cs
> +        timeSpanString = timeSpanString.Trim();
> Doesn't Discord trim strings before sending them as slash command inputs?
only at the beginning

2023-12-28 08:51 UTC, Octol1ttle commented on src/Parsers/TimeSpanParser.cs
> +        timeSpanString = timeSpanString.Trim();
in that case, strings should come trimmed, the parser shouldn't need to do extra work

2023-12-28 08:57 UTC, mctaylors commented on src/Parsers/TimeSpanParser.cs
> +        timeSpanString = timeSpanString.Trim();
but what if user will enter `5 min` string?

2023-12-28 08:58 UTC, Octol1ttle commented on src/Parsers/TimeSpanParser.cs
> +        timeSpanString = timeSpanString.Trim();
what is the issue here?

2023-12-28 09:02 UTC, mctaylors commented on src/Parsers/TimeSpanParser.cs
> +        timeSpanString = timeSpanString.Trim();
strings come without spaces only *at the beginning and at the end*, between actual characters spaces will remain. won't the parser get confused if there is a space between the number and the unit (?) type?

2023-12-28 09:04 UTC, Octol1ttle commented on src/Parsers/TimeSpanParser.cs
> +        timeSpanString = timeSpanString.Trim();
> won't the parser get confused if there is a space between the number and the unit (?) type?
if that's the case, then the current version of your code shouldn't even work.

2023-12-29 17:39 UTC, Octol1ttle requested changes

2023-12-29 17:39 UTC, Octol1ttle commented on src/Commands/RemindCommandGroup.cs
> +using TimeSpanParser = Octobot.Parsers.TimeSpanParser;
use a normal `using`

2023-12-29 17:39 UTC, Octol1ttle commented on src/Parsers/TimeSpanParser.cs
> +            return TimeSpan.Zero;
This should return an error instead of Zero

2023-12-30 19:00 UTC, Octol1ttle requested changes

2023-12-31 10:51 UTC, Octol1ttle requested changes

2023-12-31 10:51 UTC, Octol1ttle commented on src/Parsers/TimeSpanParser.cs
> +                    return TimeSpan.Zero;
Once again you are returning `Zero` instead of an error.

2023-12-31 10:51 UTC, Octol1ttle commented on src/Parsers/TimeSpanParser.cs
> +    /// </remarks>
```suggestion
    /// <summary>
    ///     Parses a <see cref="TimeSpan"/> from the <paramref name="timeSpanString"/>.
    /// </summary>
    /// <returns>
    ///     The parsed <see cref="TimeSpan"/>, or <see cref="ArgumentInvalidError"/> if parsing failed.
    /// </returns>
```

2023-12-31 10:51 UTC, Octol1ttle commented on src/Commands/RemindCommandGroup.cs
> +        string stringTimeSpan,
The parameter is called `stringTimeSpan` here, but `timeSpanString` in the parser.

2023-12-31 10:53 UTC, mctaylors commented on src/Parsers/TimeSpanParser.cs
> +                    return TimeSpan.Zero;
wait how did I missed that...

2023-12-31 11:17 UTC, Octol1ttle requested changes

2023-12-31 11:17 UTC, Octol1ttle commented on src/Parsers/TimeSpanParser.cs
> +            : ParseFromRegex(matches);
Invert

2023-12-31 11:17 UTC, Octol1ttle commented on src/Parsers/TimeSpanParser.cs
> +                    !int.TryParse(groupValue, out var parsedIntegerValue))
If the intent is to support `double`s (like `3.5d`), then this code won't work. The input value has to be an integer as per the second condition.
If that is not the intent, the first condition can be omitted (as `int`s are implicitly casted to `double`s when needed)

2023-12-31 11:17 UTC, Octol1ttle commented on src/Parsers/TimeSpanParser.cs
> +                    return new ArgumentInvalidError(nameof(groupValue), "The input value encountered a parsing error.");
```suggestion
                    return new ArgumentInvalidError(nameof(groupValue), "The input value was not an integer.");
```

2023-12-31 11:20 UTC, mctaylors commented on src/Parsers/TimeSpanParser.cs
> +            : ParseFromRegex(matches);
I cannot, see https://github.com/LabsDevelopment/Octobot/actions/runs/7370013830/job/20055931614

2023-12-31 11:21 UTC, Octol1ttle commented on src/Parsers/TimeSpanParser.cs
> +            : ParseFromRegex(matches);
*sigh*
```suggestion
        return matches.Count > 0
            ? ParseFromRegex(matches)
            : new ArgumentInvalidError(nameof(timeSpanString), "The regex did not produce any matches.");
```

2023-12-31 11:34 UTC, Octol1ttle requested changes
The issues highlighted [in my original review](https://github.com/LabsDevelopment/Octobot/pull/223#pullrequestreview-1786032829) haven't been resolved.

2023-12-31 11:34 UTC, Octol1ttle commented on src/Parsers/TimeSpanParser.cs
> +    [GeneratedRegex("(?<Years>\\d+(?=y|л|г))|(?<Months>\\d+(?=mo|мес))|(?<Weeks>\\d+(?=w|н|нед))|(?<Days>\\d+(?=d|дн))|(?<Hours>\\d+(?=h|ч))|(?<Minutes>\\d+(?=m|min|мин|м))|(?<Seconds>\\d+(?=s|sec|с|
Doesn't look like it's possible to use `д` for days

2023-12-31 12:16 UTC, Octol1ttle approved these changes

2023-12-31 12:27 UTC, merged